<script lang="ts">
 import { X,ArrowUpRight } from 'lucide-svelte';
 import { scenario } from '../lib/store';
 import { bodies,AU } from '../lib/catalog';
 import { positions,distance,type Ephemeris } from '../lib/ephemeris';
 let {data,onclose}:{data:Ephemeris;onclose:()=>void}=$props();
 let from=$state('earth'),to=$state('mars');
 const start=$derived($scenario.start),end=$derived($scenario.end);
 const samples=$derived.by(()=>Array.from({length:100},(_,i)=>{const p=positions(data,start+(end-start)*i/99);return distance(p[from],p[to]);}));
 const low=$derived(Math.min(...samples)),high=$derived(Math.max(...samples));
 const path=$derived(samples.map((v,i)=>`${i===0?'M':'L'}${i/99*264+8},${130-(v-low)/(high-low||1)*108}`).join(' '));
 const current=$derived.by(()=>{const p=positions(data,$scenario.time);return distance(p[from],p[to]);});
</script>
<aside class="panel chart-panel"><div class="panel-heading"><div><span class="eyebrow">PHYSICAL MEASUREMENTS</span><h2>Distance explorer</h2></div><button aria-label="Close charts" onclick={onclose}><X size={18}/></button></div><div class="panel-section"><div class="chart-selects"><select aria-label="Distance from" bind:value={from}>{#each bodies as b}<option value={b.id}>{b.name}</option>{/each}</select><ArrowUpRight size={17}/><select aria-label="Distance to" bind:value={to}>{#each bodies as b}<option value={b.id}>{b.name}</option>{/each}</select></div><div class="metric">{current.toFixed(4)} <span>AU</span></div><div class="metric-sub">{(current*AU).toLocaleString('en-GB',{maximumFractionDigits:0})} km · current separation</div><svg class="distance-chart" viewBox="0 0 280 154" role="img" aria-label="Distance over selected simulation range"><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#ddb985" stop-opacity="0.25"/><stop offset="100%" stop-color="#ddb985" stop-opacity="0"/></linearGradient></defs>{#each [22,58,94,130] as y}<line x1="8" x2="272" y1={y} y2={y} stroke="#ffffff12"/>{/each}<path d={path+' L272,146 L8,146 Z'} fill="url(#chart-fill)"/><path d={path} fill="none" stroke="#ddb985" stroke-width="1.5"/><line x1={8+264*($scenario.time-$scenario.start)/($scenario.end-$scenario.start)} x2={8+264*($scenario.time-$scenario.start)/($scenario.end-$scenario.start)} y1="12" y2="146" stroke="#a9bfd8" stroke-dasharray="3 4"/></svg><div class="range-ends"><span>{new Date($scenario.start).getUTCFullYear()}</span><span>{new Date($scenario.end).getUTCFullYear()}</span></div><div class="chart-stats"><div><span>MIN (SAMPLED)</span><strong>{low.toFixed(4)} AU</strong></div><div><span>MAX (SAMPLED)</span><strong>{high.toFixed(4)} AU</strong></div></div><p class="hint">100 samples across your selected time range. Distances use physical coordinates, independent of view magnification.</p></div></aside>
