<script lang="ts">
 import { onMount } from 'svelte';
 import { Orbit,SlidersHorizontal,ChartNoAxesCombined,Save,Download,Upload,Info,X,Plus } from 'lucide-svelte';
 import { scenario,status,save,startClock } from './lib/store';
 import { defaultScenario,validateScenario } from './lib/scenario';
 import { positions,type Ephemeris } from './lib/ephemeris';
 import { focus } from './lib/focus';
 import ViewTree from './components/ViewTree.svelte';
 import Settings from './components/Settings.svelte';
 import Charts from './components/Charts.svelte';
 import Timeline from './components/Timeline.svelte';
 let data=$state.raw<Ephemeris|null>(null),error=$state(''),settings=$state(true),charts=$state(false),about=$state(false);let fileInput:HTMLInputElement;
 const simulationTime=$derived($scenario.time);
 const physicalPositions=$derived(data?positions(data,simulationTime):{});
 onMount(()=>{const stop=startClock();const abort=new AbortController();fetch('/data/ephemeris.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('Orbital data unavailable');return r.json();}).then(d=>data=d).catch(e=>{if(e.name!=='AbortError')error=e.message;});return ()=>{stop();abort.abort();};});
 function exportSession(){save();const url=URL.createObjectURL(new Blob([JSON.stringify($scenario,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='solar-scenario.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function importSession(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;try{if(file.size>100000)throw new Error('Scenario file is too large.');const next=validateScenario(JSON.parse(await file.text()));next.playing=false;scenario.set(next);save();status.set('Scenario imported · paused');}catch(e){status.set(`Import failed: ${(e as Error).message}`);}input.value='';}
</script>
<svelte:head><meta name="description" content="A personal solar observatory. Explore the planets and moons through synchronized, independent views."/></svelte:head>
<div class="app-shell">
 <header class="app-header"><a class="brand" href="/" aria-label="Solar Observatory home"><div class="brand-symbol"><Orbit size={26} strokeWidth={1.2}/></div><div><strong>SOLAR<span>OBSERVATORY</span></strong><small>A WINDOW INTO OUR SOLAR SYSTEM</small></div></a><div class="header-center"><span class="live-dot"></span>EXPLORATION WORKSPACE</div><nav aria-label="Main menu"><button class:pressed={charts} title="Distance charts" aria-label="Toggle charts" onclick={()=>charts=!charts}><ChartNoAxesCombined size={19}/></button><button class:pressed={settings} title="View settings" aria-label="Toggle settings" onclick={()=>settings=!settings}><SlidersHorizontal size={19}/></button><div class="divider"></div><button title="Save session" aria-label="Save session" onclick={save}><Save size={18}/></button><button title="Export scenario" aria-label="Export scenario" onclick={exportSession}><Download size={18}/></button><button title="Import scenario" aria-label="Import scenario" onclick={()=>fileInput.click()}><Upload size={18}/></button><button title="About & sources" aria-label="About and sources" onclick={()=>about=true}><Info size={18}/></button></nav><input class="hidden" type="file" accept="application/json,.json" bind:this={fileInput} onchange={importSession}/></header>
 <div class="workspace-bar"><div><span class="eyebrow">SCENARIO</span><input aria-label="Scenario name" maxlength="120" value={$scenario.name} onchange={e=>scenario.update(s=>({...s,name:e.currentTarget.value}))}/></div><div class="quick-views"><span>EXPLORE</span><button onclick={()=>focus($scenario.active,'sun')}>Solar system</button><button onclick={()=>focus($scenario.active,'earth')}>Earth & Moon</button><button onclick={()=>focus($scenario.active,'saturn')}>Saturn</button></div><button class="new-session" title="Save current session and start a new one" onclick={()=>{exportSession();scenario.set(defaultScenario());save();}}><Plus size={14}/> New</button></div>
 <main><div class="view-area">{#if error}<div class="loading"><h2>Unable to load the observatory</h2><p>{error}. Run <code>npm run data</code> to restore the bundled data.</p><button onclick={()=>location.reload()}>Retry</button></div>{:else if data}<ViewTree node={$scenario.layout} {data} positions={physicalPositions}/>{:else}<div class="loading"><Orbit size={40}/><h2>Preparing your observatory</h2><p>Loading orbital elements from the local dataset…</p></div>{/if}</div>{#if settings}<Settings positions={physicalPositions} onclose={()=>settings=false}/>{/if}{#if charts&&data}<Charts {data} onclose={()=>charts=false}/>{/if}</main>
 <Timeline/>
 <div class="status-bar"><span role="status">{$status}</span><span>JPL HORIZONS <i>·</i> 2025–2030 <i>·</i> {$scenario.views.length} {$scenario.views.length===1?'VIEW':'VIEWS'}</span></div>
</div>
{#if about}<div class="modal-backdrop" role="presentation"><div class="about-modal" role="dialog" aria-modal="true" aria-label="About Solar Observatory" tabindex="-1"><button class="modal-close" aria-label="Close about" onclick={()=>about=false}><X size={20}/></button><Orbit size={32}/><span class="eyebrow">SOLAR OBSERVATORY / 0.1</span><h1>A shared universe.<br/>Your perspective.</h1><p>Eight planets. Twelve moons. One shared clock. Split the sky into independent views, follow a world, and return to a saved exploration.</p><h3>Data & accuracy</h3><p>Orbital elements downloaded from <a href="https://ssd.jpl.nasa.gov/horizons/" target="_blank" rel="noreferrer">NASA/JPL Horizons</a>. Planet elements are sampled every 8 days; moon elements daily. Kepler propagation is smoothly blended between epochs. Positions are approximate and have not yet been checked against reference ephemerides.</p><p>J2000 ecliptic coordinates. Dates are shown in UTC; conversion to ephemeris time assumes 37 leap seconds. Axial rotation and pole directions use the polynomial terms of <a href="https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/pck00011.tpc" target="_blank" rel="noreferrer">NASA/JPL NAIF planetary rotation models</a>. Periodic libration/nutation, differential solar rotation, atmospheric winds and eclipses are not modeled. Texture longitude registration is approximate. Untextured moons use representative colors.</p><h3>Image credits</h3><p>Sun, planet and Moon maps by <a href="https://www.solarsystemscope.com/textures/" target="_blank" rel="noreferrer">Solar System Scope / INOVE</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a>. Rendered with lighting and display magnification. The star field uses the full-resolution 8K HDR J2000 map from <a href="https://svs.gsfc.nasa.gov/4851/" target="_blank" rel="noreferrer">NASA/Goddard Space Flight Center Scientific Visualization Studio</a> (Ernie Wright), Deep Star Maps 2020. Gaia DR2: ESA/Gaia/DPAC. Constellation figures are based on designs for the IAU by Alan MacRobert, Sky and Telescope (Roger Sinnott and Rick Fienberg). Sky brightness is enhanced for visibility; proper motion and stellar parallax are not modeled.</p><h3>On the horizon</h3><p>Physical rocket flight, asteroids, satellites, Earth-surface observations, and a configurable LLM connection through a local server.</p><button class="primary-button" onclick={()=>about=false}>Back to exploring</button></div></div>{/if}

